server:
  port: 9056
  
osm.service.url: http://localhost:9055/osmfallout/osmOrderCleanUpByTask
osm.service.username: username
osm.service.password: password

logging.config: config/logback.xml

pack:
   database:
     driver.class: oracle.jdbc.OracleDriver
     url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=servicaName)))
     username: uid
     password: password
     init.pool.size: 4
     max.pool.size: 10
   
osm.service.fallout.moveindate : 08-APR-20
osm.service.fallout.task : UpdateServiceConfiginUIM_FalloutTask
